--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-03-26 19:14:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 41088)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id integer NOT NULL,
    human_id integer,
    name character varying NOT NULL,
    author character varying,
    year_of_publication integer NOT NULL
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 41087)
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 41057)
-- Name: human; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.human (
    id integer NOT NULL,
    full_name character varying NOT NULL,
    year_of_birth integer NOT NULL
);


ALTER TABLE public.human OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 41056)
-- Name: people_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.human ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3333 (class 0 OID 41088)
-- Dependencies: 217
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.book (id, human_id, name, author, year_of_publication) VALUES (5, NULL, 'Метро 2034', 'Дмитрий Глуховский', 2009);
INSERT INTO public.book (id, human_id, name, author, year_of_publication) VALUES (6, 7, 'Собор Парижской Богоматери', 'Виктор Гюго', 2013);
INSERT INTO public.book (id, human_id, name, author, year_of_publication) VALUES (4, 15, 'Война и мир', 'Лев Николаевич Толстой', 1959);
INSERT INTO public.book (id, human_id, name, author, year_of_publication) VALUES (7, 3, 'Философия Java', 'Брюс Эккель', 2017);


--
-- TOC entry 3331 (class 0 OID 41057)
-- Dependencies: 215
-- Data for Name: human; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.human (id, full_name, year_of_birth) VALUES (3, 'Вешников Александр Борисович', 1983);
INSERT INTO public.human (id, full_name, year_of_birth) VALUES (15, 'Тестовый Петр Петрович', 1916);
INSERT INTO public.human (id, full_name, year_of_birth) VALUES (7, 'Таран Григорий Валерьевич', 1996);


--
-- TOC entry 3339 (class 0 OID 0)
-- Dependencies: 216
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_seq', 7, true);


--
-- TOC entry 3340 (class 0 OID 0)
-- Dependencies: 214
-- Name: people_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.people_id_seq', 16, true);


--
-- TOC entry 3185 (class 2606 OID 41094)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- TOC entry 3179 (class 2606 OID 49312)
-- Name: human human_full_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human
    ADD CONSTRAINT human_full_name_key UNIQUE (full_name);


--
-- TOC entry 3181 (class 2606 OID 41065)
-- Name: human people_fio_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human
    ADD CONSTRAINT people_fio_key UNIQUE (full_name);


--
-- TOC entry 3183 (class 2606 OID 41063)
-- Name: human people_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human
    ADD CONSTRAINT people_pkey PRIMARY KEY (id);


--
-- TOC entry 3186 (class 2606 OID 41095)
-- Name: book book_human_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_human_id_fkey FOREIGN KEY (human_id) REFERENCES public.human(id) ON DELETE SET NULL;


--
-- TOC entry 3187 (class 2606 OID 49306)
-- Name: book book_human_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_human_id_fkey1 FOREIGN KEY (human_id) REFERENCES public.human(id) ON DELETE SET NULL;


-- Completed on 2023-03-26 19:14:29

--
-- PostgreSQL database dump complete
--

